use_frameworks!

target 'RTRootNavigationController_Swift_Example' do
  pod 'RTRootNavigationController_Swift', :path => '../'

  target 'RTRootNavigationController_Swift_Tests' do
    inherit! :search_paths

    
  end
end
